spring.data.mongodb.uri= mongodb+srv://pratishthadhote:prati%40atlas@cluster0.if2dh24.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=journaldb
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword
spring.data.mongodb.auto-index-creation = true

